---
title: "S. pombe polymorphism statistics"
output:
  html_document:
    css: style.css
runtime: shiny
---

```{r library, echo=FALSE, message=FALSE}
library(pipeR)
library(dplyr)
library(ggplot2)
```

```{r input, echo=FALSE}
inputPanel(
    sliderInput('width', 'Width', 6, min=1, max=6),
    numericInput('thr_p', HTML('Threshold for &theta;&pi;'), 0.007, min=0, max=1, 0.001),
    numericInput('thr_d', "Threshold for Tajima's D", -0.01, min=-2, max=2, 0.01)
)
```

```{r render, echo=FALSE}
tbl = read.delim('data/pombe-mean.tsv.gz', stringsAsFactor=FALSE)

filtered = reactive({tbl %>>%
    filter(nchar(oligo)==(input$width * 2 + 1)) %>>%
    mutate(interest=theta_pi<input$thr_p & TajimasD<input$thr_d)
})

renderPlot(
    filtered() %>>%
    ggplot(aes(theta_pi, TajimasD, colour=interest)) +
    geom_vline(xintercept=0, colour='gray') +
    geom_hline(yintercept=0, colour='gray') +
    geom_point() +
    geom_vline(xintercept=input$thr_p, colour='orangered') +
    geom_hline(yintercept=input$thr_d, colour='orangered') +
    scale_colour_discrete(h.start=180) +
    labs(x=expression(theta[pi]), y="Tajima's D") +
    theme(text=element_text(size=20))+
    theme(legend.position='none'),
    height = 600,
    width = 600
)

renderDataTable(
    filtered() %>>% filter(interest),
    options=list(pageLength=50, order=list(list(3, 'asc')))
)
```
