---
title: "Evenness of 6-mer occurrence in *S. pombe* genome"
output: html_document
runtime: shiny
---

あらゆる6-mer配列のなかで、
ゲノム上に固まっているものはあるか？
逆に、ランダムよりも均等に配置されているものはあるか？

ゲノムを20kbごとに区切った断片においてそれぞれの6-mer配列の出現頻度を数え、
平均と分散を計算してプロットした。
塩基配列がランダムな並びであれば、6-merの出現頻度は平均=分散のポアソン分布に従うと考えられる。
分散/平均 (variance-mean ratio) が小さいほど一様分布、大きいほど集中分布になる。
下図の黒い直線は分散=平均。

塩基組成を維持したままシャッフルした場合、おおむね直線上に乗り、
平均値はAT vs GCの比率によって決まる。
(ゲノムがAT-richなので一番右の島はAとTのみを含む6-mer配列)

[→ 個々の配列のゲノム上での分布を見る](../distribution/)\
[→ 全6-merの保存性を多型データで見る](../polymorphism/)

```{r library, echo=FALSE, message=FALSE}
library(stringr)
library(pipeR)
library(plyr)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r input, echo=FALSE}
.cache = 'coefvar-ref.csv.gz'
.ref = read.table(.cache, header=TRUE, stringsAsFactors=FALSE) %>>% tbl_df()
.chrs = unique(as.character(.ref$chr))
names(.chrs) = .chrs
inputPanel(
    checkboxGroupInput('chr', 'Chromosome:', .chrs, c('randomized', 'total')),
    checkboxInput('exclude', 'Exclude repetitive region 688500:698500 in chr2, telomeres, and centromeres'),
    sliderInput('ubound', 'Display x max:', 5, 150, 100, 5)
)
```

```{r render, echo=FALSE}
filtered = reactive({
    .data = if (input$exclude) {
        read.table('coefvar-intermere.csv.gz', header=TRUE, stringsAsFactors=FALSE)
    } else {
        .ref
    }
    subset(.data, chr %in% input$chr) %>>%
        dplyr::filter(mean < input$ubound)
})

.range = reactive(range(filtered()$mean))

output$plot = renderPlotly(filtered() %>>% {
    ggplot(., aes(mean, var))+
    geom_point(aes(text=motif, colour=chr), alpha=0.6)+
    geom_line(data=data_frame(mean=.range(), var=.range()))+
    theme_bw()
    } %>>% ggplotly(tooltip=c('text', 'x', 'y', 'colour'))
)
plotlyOutput('plot', width='720px', height='600px')

if (FALSE) {
    renderPlot(filtered() %>>%
        ggplot(aes(mean, sd))+
        geom_point(aes(colour=chr), alpha=0.6)+
        geom_line(data=data_frame(mean=.range(), sd=.range()))+
        theme_bw()
    )
}

#renderDataTable(filtered())
renderDataTable(filtered(), options=list(order=list(c(5, 'asc'))))
```
